language: ruby
gemfile: Gemfile.travis
rvm:
  - 2.0.0
env:
  - DB=sqlite
script:
  - rake db:test:prepare
  - bundle exec rake spec
before_script:
  - cp config/database.travis.yml config/database.yml
  # - mysql -e 'create database antinote_test'
  # - psql -c 'create database antinote_test' -U postgres
notifications:
  email: false