language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_script:
  - cp config/database.travis.yml config/database.yml
  # - mysql -e 'create database antinote_test'
  # - psql -c 'create database antinote_test' -U postgres
notifications:
  email: false