development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  username: pwrwebppensxey
  password: O9uz-uLhLqAHgRwzyOiaWgV6-O
  database: dfm7h7m4gttqie
  host: ec2-54-227-255-156.compute-1.amazonaws.com
  port: 5432
